apiVersion: v2
name: open-webui
version: 3.7.0
appVersion: 0.3.35
home: https://www.openwebui.com/
icon: >-
  https://raw.githubusercontent.com/open-webui/open-webui/main/static/favicon.png
description: 'Open WebUI: A User-Friendly Web Interface for Chat Interactions 👋'
keywords:
  - llm
  - chat
  - web-ui
sources:
  - https://github.com/open-webui/helm-charts
  - https://github.com/open-webui/open-webui/pkgs/container/open-webui
annotations:
  licenses: MIT