apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openwebui-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
spec:
  rules:
    - http:
        paths:
        - path: /openwebui
          pathType: Prefix
          backend:
            service:
              name: open-webui
              port:
                number: 3000